# Mailtrap configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=aa3653948e2b84
spring.mail.password=2d212ffaa5b446
spring.mail.properties.mail.smtp.auth=PLAIN

# File upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB